### ISSUE TITLE
SIGABRT

### ISSUE THREAD

**Issue by umop3plsdn** [orhun/godsays#3]
I tried installing with just cargo install godsays and it isn't working unfortunately. I get the following:
thread 'main' panicked at 'Unable to read the file', /home/da5id/.cargo/registry/src/github.com-1ecc6299db9ec823/godsays-0.1.2/src/lib.rs:24:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'godsays' terminated by signal SIGABRT (Abort)

**Comment by umop3plsdn** [comment]
I did get it running straight cloning from github though

**Comment by orhun** [comment]
Hey, [ae8ccec](https://github.com/orhun/godsays/commit/ae8ccec29f793ad1a4be04d16c422056ecd5bd0d) should fix this, thanks for reporting!
